"""first migration

Revision ID: 070aace67b7b
Revises: 
Create Date: 2019-07-01 13:20:38.926206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070aace67b7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitten',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitten')
    # ### end Alembic commands ###
